
# Application
url = https://tutorialsninja.com/demo/
app_url = http://localhost/opencart/

# Browser
browser = chrome

# Timeouts
implicit.wait = 0
explicit.wait = 20
page.load.timeout = 30


# Execution
headless = false

#Credentials
email = tusharpotdar99@gmail.com
password = TushOC@1999

invalidemail = something@gmail.com
invalidpassword = something123

